# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for exia-mcp
FROM node:lts-alpine AS build

# Install dependencies
WORKDIR /app
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

RUN npm ci \
    && npm run build

# Final image
FROM node:lts-alpine
WORKDIR /app

# Copy built files and dependencies
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules

# Copy any other required assets (if any)

# Default command: user will supply args via MCP startCommand
CMD ["node", "dist/index.js"]
